services:
  phoa-web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "streamlit",
        "run",
        "streamlit_app.py",
        "--server.address=0.0.0.0",
        "--server.port=8501",
      ]
    ports:
      - "8501:8501"

  phoa-cli:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "main.py", "--no-viz", "--steps", "120"]
    profiles: ["cli"]
